name: Koyeb Keep Alive

on:
  schedule:
    # 每小时15分执行一次，避开 GitHub 高峰
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up Koyeb Services
        shell: bash
        run: |

          echo "========================================"
          echo "Start : $(date -u)"
          echo "Event : $GITHUB_EVENT_NAME"
          echo "========================================"

          URLS=(
            "https://supposed-timi-ajgboqr-f5dc4042.koyeb.app"
            "https://angry-gretna-fangqin097-9c826f86.koyeb.app"
          )

          AGENTS=(
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
          "Mozilla/5.0 (X11; Linux x86_64)"
          "Mozilla/5.0 (Linux; Android 15)"
          "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)"
          )

          TOTAL=${#URLS[@]}
          COUNT=0

          for URL in "${URLS[@]}"
          do
              COUNT=$((COUNT+1))

              UA=${AGENTS[$RANDOM % ${#AGENTS[@]}]}

              echo ""
              echo "----------------------------------------"
              echo "[$COUNT/$TOTAL] $URL"

              START=$(date +%s)

              curl \
                -L \
                --connect-timeout 10 \
                --max-time 25 \
                --retry 1 \
                --retry-delay 2 \
                --user-agent "$UA" \
                --silent \
                --output /dev/null \
                "$URL" >/dev/null 2>&1 || true

              END=$(date +%s)

              echo "Finished in $((END-START)) sec"

              SLEEP=$((RANDOM % 6 + 3))
              echo "Sleep ${SLEEP}s"
              sleep "$SLEEP"

          done

          echo ""
          echo "========================================"
          echo "Visited $TOTAL URL(s)"
          echo "Finish : $(date -u)"
          echo "========================================"

          exit 0
