name: Koyeb Keep Alive

on:
  schedule:
    # 每30分钟执行一次
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up Koyeb Services
        shell: bash
        run: |

          echo "======================================"
          echo "Start: $(date)"
          echo "======================================"

          ###################################################
          # 修改这里，填写你的域名
          ###################################################
          URLS=(
            "https://koy.621011.xyz"
            #"https://node2.xxx.com"
            #"https://node3.xxx.com"
          )

          ###################################################
          # 随机浏览器
          ###################################################
          AGENTS=(
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
          "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
          "Mozilla/5.0 (X11; Linux x86_64)"
          "Mozilla/5.0 (Linux; Android 15)"
          "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)"
          )

          TOTAL=${#URLS[@]}

          for URL in "${URLS[@]}"
          do

            UA=${AGENTS[$RANDOM % ${#AGENTS[@]}]}

            echo ""
            echo "--------------------------------------"
            echo "Visiting: $URL"

            # 只访问，不判断结果
            curl \
              -L \
              --connect-timeout 15 \
              --max-time 40 \
              --retry 2 \
              --retry-delay 3 \
              -A "$UA" \
              -s \
              -o /dev/null \
              "$URL" || true

            echo "✓ Request finished"

            SLEEP=$((RANDOM % 8 + 3))
            echo "Sleep ${SLEEP}s..."
            sleep "$SLEEP"

          done

          echo ""
          echo "======================================"
          echo "Finished: $(date)"
          echo "Visited ${TOTAL} URL(s)"
          echo "======================================"

          exit 0
